//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCorrection.Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QuestionGrade> QuestionGrade { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Candidate> Candidate { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<QuestionResult> QuestionResult { get; set; }
        public virtual DbSet<ImageCandidate> ImageCandidate { get; set; }
    }
}
